#!/bin/bash

set -e

# functions

## core functions

function welcomeprompt {
echo "Welcome to WLinux."
echo 
echo "WLinux comes with a core set of packages. This script allows you to install optional sets of packages."
echo
}

function continueprompt {
read -r -p "Would you like to continue setup? [Y/n] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
    echo "Continuing with setup."
else
    echo "You may run the script again any time by running: bash /etc/setup"
    quit
fi
}

function quit {
exit
}

function updatescriptprompt {
read -r -p "Would you like to download and run an updated version of this setup from the GitHub? [Y/n] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])+$ ]]
then
    TMPDIR=$(mktemp -d)
    curl https://raw.githubusercontent.com/WhitewaterFoundry/WLinux/sirredbeard/linux_files/setup | | bash -s -- u
    quit
else
    echo "Continuing with defualt install script."
fi
}

## package meta function

function installpackages {
zshinstall
fishinstall
neoviminstall
}

## individual package install functions

function zshinstall {
}

function fishinstall {
}

function neoviminstall {
}

# main

## process update command line flag

while getopts ":u" opt; do
  case ${opt} in
    u ) $updateflag=true
      ;;
  esac
done

## setup script

if $updateflag
then
  installpackages
else
  welcomeprompt
  continueprompt
  updatescriptprompt
  installpackages
fi
