#!/bin/bash

# placeholder for out of box experience script

# add zsh/ohmyzsh?

# add fish/ohmyfish?

# add neovim?

# add vs code?

# add azure tools?

# add aws tools?

# add python?

# add ruby?

# add haskell?

# add rust?

# add xorg?
